name: 'Report macOS'

on:
  workflow_run:
    workflows: ['macOS']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: Trick_macos
        path: . # download the artifact in the current directory
    
    - name: Report the test results 
      uses: dorny/test-reporter@v1
      with:
        name: Results_Trick_macos # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
