name: 'Report Linux Python 2'

on:
  workflow_run:
    workflows: ['Linux Python 2']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    strategy:
      fail-fast: false
      matrix:
        cfg:
#-------- Operating Systems ----------------
          - { os: ubuntu,      tag: 22.04,    arch: debian, arch_ver: 12 }
          - { os: rockylinux,  tag: 8,        arch: rhel,   arch_ver: 8  }
          - { os: oraclelinux, tag: 8,        arch: rhel,   arch_ver: 8  }
        python: [2]


    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: Trick_${{matrix.cfg.os}}${{matrix.cfg.tag}}_py${{matrix.python}}
        path: . # download the artifact in the current directory

    - name: Report the test results
      uses: dorny/test-reporter@v1
      with:
        name: Results_Trick_${{matrix.cfg.os}}${{matrix.cfg.tag}}_py${{matrix.python}} # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
